# Generated by Django 3.2.6 on 2021-09-05 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_text', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.SmallIntegerField()),
                ('ques_title', models.TextField()),
                ('posted_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_text', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.SmallIntegerField()),
                ('answered_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.questions')),
            ],
        ),
    ]
