# Generated by Django 3.2.6 on 2021-09-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='upvotes',
        ),
    ]
